laminlabs/lnschema-core

lnschema_core/dev/sqlmodel.py

- https://github.com/laminlabs/lnschema-wetlab/pull/50

✨ `add_relationship_keys` function

---

docs/guide/tables.ipynb
docs/guide/test-data-validation.ipynb
lnschema_core/dev/sqlmodel.py

:adhesive_bandage: Fix error message in `Relationship` type checking

---

docs/guide/test-data-validation.ipynb
lnschema_core/dev/sqlmodel.py

Do not resolve forward references for resolved relationships.

:bug: Fix strict type checking for relationships

---

lnschema_core/__init__.py
lnschema_core/_core.py
lnschema_core/dev/_storage.py
lnschema_core/migrations/versions/2023-02-22-6952574e2d49-vx_x_x.py

with https://github.com/laminlabs/lamindb/pull/503

✨ Create DFolder from a folder

---

.pre-commit-config.yaml
lnschema_core/__init__.py
lnschema_core/_core.py
lnschema_core/dev/_storage.py
lnschema_core/dev/sqlmodel.py
lnschema_core/migrations/versions/2023-04-05-6de59093e378-v0_31_0.py
noxfile.py
tests/test_base.py

- https://github.com/laminlabs/lamindb/pull/614/

🚸 Use full filename to populate `File.name`, introduce `File.key` and `Folder.key`

---

lnschema_core/_core.py

✨ Overwrite key in replace if needed

---

lnschema_core/_core.py

⚡️ Do not change key for in-memory data replace

---

pyproject.toml
tests/test_notebooks.py

✅ Use nbproject-test directly in test_notebooks.py

---

lnschema_core/_core.py
lnschema_core/models.py

➖ Remove nbproject from code

---

lnschema_core/models.py

- https://github.com/laminlabs/lamindb/pull/742

:recycle: Move save logic here

---

lnschema_core/models.py

- https://github.com/laminlabs/lamindb/pull/754

✨ Delete storage in File.delete

---

lnschema_core/migrations/0001_initial.py
lnschema_core/models.py

- https://github.com/laminlabs/lamindb-setup/pull/416

🍱 Add migration process for legacy SA instances

---

.pre-commit-config.yaml
lnschema_core/__init__.py
lnschema_core/models.py
lnschema_core/types.py

- https://github.com/laminlabs/lamindb/pull/813

🚚 Rename `BaseORM` to `ORM`, move `ORM` signatures here

---

lnschema_core/models.py
lnschema_core/types.py

- https://github.com/laminlabs/lndocs/pull/63

📝 Remove all duplicated type annotation from docs

---

lnschema_core/mocks.py
lnschema_core/models.py

https://github.com/laminlabs/lamindb/pull/1307

✨ Initial implementation of IndexedDataset

---

lnschema_core/models.py

https://github.com/laminlabs/lamindb/pull/1334

✨ Do virtual inner join of variables in Dataset.mapped

---

lnschema_core/models.py

https://github.com/laminlabs/lamindb/pull/1380

✨ Add outer join and categories caching to Collection.mapped

---

lnschema_core/models.py

https://github.com/laminlabs/lamindb/pull/1443

✨ Add unknown_label to Collection.mapped signature

---

lnschema_core/models.py
lnschema_core/types.py

- https://github.com/laminlabs/lamindb-setup/pull/707

♻️ Replace TypeVar with TypeAlias

---

lnschema_core/models.py

♻️ Remove map_synonyms and rename backed to open

---

noxfile.py
tests/conftest.py
tests/test_integrity.py
tests/test_models.py

Resolves:
- https://github.com/laminlabs/lnschema-core/issues/407

➖ Remove bionty & lamindb from dependencies

---

lnschema_core/models.py

Resolves: https://github.com/laminlabs/lamindb/issues/1920

🐛 Make `.versions` aware of `using`

---

lnschema_core/models.py

https://github.com/laminlabs/lamindb/pull/1940

🔥 Remove stream argument from load

---

lnschema_core/models.py

https://github.com/laminlabs/lamindb/pull/1974

✨ Allow filtering obs indices in MappedCollection based on obs column

---

lnschema_core/models.py

- Fixes #437 
- Adds a tiny bit more detail for delete docs

📝 Fix visibility docs in Artifact and Collection

---

lnschema_core/models.py

https://github.com/laminlabs/lamindb/pull/2115

✨ Stream pyarrow.dataset.dataset supported formats in Artifact.open()
